sequenceDiagram
    participant User
    participant RellenadorController
    participant RellenadorService
    participant FacturadorClient
    participant ClienteMovimientoClient
    participant OrderNoteClient
    participant TransaccionFacturaProgramaDiaClient

    User->>RellenadorController: GET /api/isolate/rellenador/auto-completa/{...}
    RellenadorController->>RellenadorService: autoCompleta(...)
    RellenadorService->>FacturadorClient: consultaComprobante(...)
    FacturadorClient-->>RellenadorService: FacturaResponseDto
    RellenadorService->>ClienteMovimientoClient: findByComprobante(...)
    alt Comprobante NO existe
        ClienteMovimientoClient-->>RellenadorService: Exception
        RellenadorService->>OrderNoteClient: findLastByNumeroDocumento(...)
        OrderNoteClient-->>RellenadorService: OrderNoteDto
        alt Importe ARCA == OrderNote
            RellenadorService->>TransaccionFacturaProgramaDiaClient: registroTransaccionFacturaProgramaDia(...)
            TransaccionFacturaProgramaDiaClient-->>RellenadorService: void
        end
    else Comprobante SI existe
        ClienteMovimientoClient-->>RellenadorService: ClienteMovimientoDto
    end
    RellenadorService-->>RellenadorController: void
    RellenadorController-->>User: ResponseEntity(OK)
